### ISSUE TITLE
Firmware sources

### ISSUE THREAD

**Issue by krishermans** [RHioTResearch/SensorTagFirmware#1]
Hi

I'm interested in reading the source of your custom firmware, just for educational purposes (I'm a researcher). Do you consider it to publish here at Github?

Thanks!

**Comment by starksm64** [comment]
The license from TI won't allow public releases of the code, but I can put the workspace as zip file someplace you can download it. Send your email to starksm64@gmail.com and I'll provide the link when it is ready.

**Comment by krishermans** [comment]
Hi

I sent you a mail with my address. Thanks for sharing!

Regards
Kris

**Comment by robinvanemden** [comment]
Same here -as a researcher at Leiden University, I would be very interested in the firmware's source code. Is there any chance you'd provide us said link to as well?

**Comment by Braklet** [comment]
Hi there, any way I could get a copy of the source code too?  I'm running your firmware on two separate Tags that I poll for weather data.

Thanks in advance!

BL

**Comment by starksm64** [comment]
So I finally just put up the code in the https://github.com/RHioTResearch/SensorTagFirmware/releases/tag/V1.0 release. It is just a snapshot of the source directory and an export of the Code Composer project. I'm sure there a bunch of dependencies one needs to install before it can be usefully imported into Code Composer.
